CREATE TABLE IF NOT EXISTS HUMANS(
	HUMAN_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(30),
    PASSWORD VARCHAR(1000) NOT NULL,
	ROLE VARCHAR(6),
	DATE DATE
	);

CREATE TABLE IF NOT EXISTS ROLES(
    ROLE_ID SERIAL PRIMARY KEY,
    SURNAME VARCHAR(30),
    EMAIL VARCHAR(50),
    NUMBER VARCHAR(30),
    EVENT_QUOTA INTEGER,
    UNIQUE(EMAIL),
    ROLE_WHICH INTEGER REFERENCES HUMANS(HUMAN_ID)
    );

CREATE TABLE IF NOT EXISTS CONTACTS(
    CONTACT_ID SERIAL PRIMARY KEY,
    CONTACT_NAME VARCHAR(30) NOT NULL,
    CONTACT_SURNAME VARCHAR(30) NOT NULL,
    CONTACT_EMAIL VARCHAR(20),
    CONTACT_NUMBER VARCHAR(20),
    CONTACT_ID_WHICH INTEGER REFERENCES HUMAN(HUMAN_ID)
    );

CREATE TABLE IF NOT EXISTS INTERVIEWS(
    INTERVIEW_ID SERIAL PRIMARY KEY,
    DATE_FROM DATE,
    DATE_TO DATE,
    COMMENT TEXT,
    INTERVIEW_ID_WHICH INTEGER REFERENCES HUMANS(HUMAN_ID)
    );

CREATE TABLE IF NOT EXISTS EVENTS(
    EVENT_ID SERIAL PRIMARY KEY,
    DATE_FROM DATE,
    DATE_TO DATE,
    COMMENT TEXT,
    STATUS VARCHAR(20),
    EVENT_ID_WHICH INTEGER REFERENCES HUMANS(HUMAN_ID)
    );